name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/leet-code-test

      - name: Download artifacts
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: dist-files

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Ветка, куда будут отправлены файлы статического сайта
          folder: dist/leet-code-test # Путь к папке с собранным проектом
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'NonEstSpes' # Ваше имя
          user_email: 'egor.bobilev2016@yandex.ru' # Ваш email
          commit_message: 'Deploy to GitHub Pages'

      - name: install json-server
        run: npm install -g json-server 
      - name: run json-server
        run: json-server -w db.json &
      - name: npm run deploy
        run: npm run deploy
      

